version: "3.0"

services:
  managed:
    build:
      context: .    
      dockerfile: Dockerfile.managed
    ports:
      - "5553:5555" # http://localhost:5553
    environment:
      - CC_SERVER=cc
      - CC_AUTO_REGISTER=1    
    volumes: 
      - ./licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml 
    links:
      - cc      

  cc:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1.0.1
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - ACCEPT_EULA=Y

  init:
    image: daerepository03.eur.ad.sag:4443/ccdevops/cli:10.1
    environment:
      - CC_SERVER=cc
    command: sagcc list landscape nodes local -e ONLINE -w 240
    links:
      - cc

  test:
    image: daerepository03.eur.ad.sag:4443/ccdevops/cli:10.1
    environment:
      - CC_SERVER=cc
    command: sagcc list monitoring state -e integrationServer-default -w 240
    links:
      - managed
      - cc
